baseURL: "https://kevinchen1994.github.io/"
theme: hugo-PaperMod
languageCode: "en-us"
title: "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: /posts/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Categories
          url: /categories/
          weight: 15
        - name: About me
          url: /about/
          weight: 20
          
params:
    env: production
    homeInfoParams:
        Title: "Test: my, garden!"
        Content: ğŸ‘‹å—¨ï¼Œæˆ‘æ˜¯Kevinï¼Œä¸€ä¸ªè‡ªç„¶è¯­è¨€å¤„ç†ç®—æ³•å·¥ç¨‹å¸ˆï¼Œæ›´æ˜¯ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´ï¼ŒINFJ-Aã€‚

                - åæ ‡åŒ—äº¬ï¼Œäº’è”ç½‘è¡Œä¸šï¼Œå–œæ¬¢ç”µå½±ã€é˜…è¯»ã€è·‘æ­¥ï¼Œå…³æ³¨äº’è”ç½‘è¡Œä¸šã€ç§‘æŠ€è¡Œä¸šã€æ–°èƒ½æºæ±½è½¦è¡Œä¸šä»¥åŠFIREè¿åŠ¨ã€‚
                - è¿™ä¸ªåšå®¢åç§°æ˜¯å› ä¸ºæˆ‘å–œæ¬¢ã€ŠBreaking Badã€‹(ç»å‘½æ¯’å¸ˆ)ï¼Œä¸»è§’å°±å«è€ç™½ï¼Œç»°å·æµ·æ£®å ¡ï¼ŒåŒæ—¶ä»–åœ¨å‰§é‡Œä»äº‹åŒ–å­¦åˆ¶æ¯’ï¼Œè¡Œè¯cookï¼Œæ‰€ä»¥æˆ‘å°±å–åä¸ºå¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿ï¼Œå•çº¯æ˜¯ä¸ºäº†ææ€ªã€‚
                - è¿™ä¸ªåšå®¢æˆ‘ä¼šæ€»ç»“ä¸€äº›æŠ€æœ¯ç›¸å…³è¯é¢˜ï¼Œå¹³æ—¶çš„æ„Ÿæƒ³ï¼Œæ‚ä¸ƒæ‚å…«çš„è¯é¢˜ï¼Œè¿™é‡Œå°±æ˜¯æˆ‘çš„è‡ªç•™åœ°äº†ï¼Œä½ å¯ä»¥é€šè¿‡æ ‡ç­¾é˜…è¯»æ„Ÿå…´è¶£çš„è¯é¢˜ã€‚
                - å¦‚æœä½ å¯¹æˆ‘æˆ–è€…æˆ‘å†™çš„ä¸œè¥¿æ„Ÿå…´è¶£çš„è¯ï¼Œæ¬¢è¿äº¤æµğŸ“®346521888@qq.comã€‚
                
      

    socialIcons:
        - name: twitter
          url: "https://test.com/"
        - name: stackoverflow
          url: "https://test.com/"
        - name: github
          url: "https://test.com/"
        - name: medium
          url: "https://test.com/"
        - name: linkedin
          url: "https://test.com/"

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"