baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "hugo-PaperMod"

# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."



[params]
# ä¸»é¡µä¿¡æ¯è®¾ç½®
  [params.homeInfoParams]
    title = "kevin"
    # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
    content = "ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer"

  [params.socialIcons]
    - name = "github"
      url = "https://github.com/kevinchen1994"
    - name = "email"
      url = "346521888@qq.com"


# èœå•é…ç½®
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "æ‰€æœ‰æ–‡ç« "
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "æ ‡ç­¾"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "ç±»åˆ«"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 5

# æ–‡ç« é¡µé¢é…ç½®
[page]
  # æ˜¯å¦ä½¿ç”¨ç³»åˆ—å¯¼èˆª
  seriesNavigation = true
  # æ˜¯å¦å¯ç”¨æœ€åä¿®æ”¹æ—¶é—´
  enableLastMod = true
  # æ˜¯å¦å¯ç”¨å­—æ•°ç»Ÿè®¡
  enableWordCount = true
  # æ˜¯å¦å¯ç”¨é˜…è¯»æ—¶é—´ä¼°è®¡
  enableReadingTime = true
   # ç›®å½•é…ç½®
  [page.toc]
    # æ˜¯å¦ä½¿ç”¨ç›®å½•
    enable = true
    # æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
    keepStatic = false
    # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
    auto = true
  # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
  [page.share]
    enable = true
    Twitter = true
    Weibo = true