baseURL: "https://kevinchen1994.github.io/"
theme: hugo-PaperMod
languageCode: "en-us"
title: "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: /posts/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10
        - name: Categories
          url: /categories/
          weight: 15
        - name: Search
          url: /search/
          weight: 20  
        - name: About Me
          url: /about/
          weight: 25
          
params:
    env: production
    homeInfoParams:
        Title: "æ¬¢è¿æ¥åˆ°æˆ‘çš„å¨æˆ¿"
        Content: "ğŸ‘‹å—¨ï¼Œæˆ‘æ˜¯Kevinï¼Œä¸€ä¸ªè‡ªç„¶è¯­è¨€å¤„ç†ç®—æ³•å·¥ç¨‹å¸ˆï¼Œæ›´æ˜¯ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´ï¼ŒINFJ-Aã€‚\n

                  \n

                  ç¬”è®°æ˜¯æ€»ç»“çŸ¥è¯†å¢æ´æœªæ¥çš„è‡ªå·±ï¼Œå†™ä½œæ˜¯å¯¹æœªæ¥è¦è®¤è¯†ä½ çš„äººçš„è‡ªæˆ‘ä»‹ç»ã€‚\n\n

                  è¿™ä¸ªåšå®¢ä¸»è¦ç”¨æ¥è®°å½•æˆ‘çš„å­¦ä¹ ã€ç”Ÿæ´»ã€æ€è€ƒï¼Œä½ å¯ä»¥é€šè¿‡æ ‡ç­¾ç­›é€‰ä½ æ„Ÿå…´è¶£çš„å†…å®¹ã€‚\n\n
                  
                  å¦‚æœä½ æƒ³äº†è§£æˆ‘ï¼Œå¯ä»¥åœ¨About Meé¡µé¢è¿›è¡ŒæŸ¥çœ‹ã€‚\n\n"
                
    socialIcons:
        - name: github
          url: "https://github.com/kevinchen1994"

    # share button      
    ShowShareButtons: true
    # showreading time
    ShowReadingTime: true

    ShowPostNavLinks: true
    # Code copy button
    ShowCodeCopyButtons: true

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


    