baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "DoIt"

[params.home.profile]
  # Gravatar é‚®ç®±, ç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
  gravatarEmail = "346521888@qq.com"
  # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
  avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
  # å¤´åƒçš„é“¾æ¥æŒ‡å‘çš„ URL
  avatarLinkURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"

[params.social]
  [params.social.email]
    # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
    weight = 10
    # ä½ çš„ç¤¾äº¤ ID
    id = "346521888@qq.com"
    # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
    prefix = ""
    # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
    title = "Email"
  [params.social.github]
    # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
    weight = 0
    # ä½ çš„ç¤¾äº¤ ID
    id = "kevinchen1994"
    # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
    prefix = "https://github.com/"
    # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
    title = "GitHub"


# paper é…ç½®
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page

# ------------------------------
# é…ç½®ç½‘ç«™èœå•
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10
#  [[menu.main]]
#    identifier = "friends"
#    name = "Friends"
#    url = "/friends/"
#    weight = 10
