baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "DoIt"
# é»˜è®¤æ¯é¡µåˆ—è¡¨æ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®
paginate = 10
# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."




# èœå•é…ç½®
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    name = ""
    url = "https://github.com/kevinchen1994"
    weight = 10

[params]
# ä¸»é¡µä¿¡æ¯è®¾ç½®
  [params.home]
    [params.home.profile]
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = "kevin"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
      subtitle = "ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer"
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = "346521888@qq.com"
  [params.social]
    [params.social.Email]
      # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
      weight = 10
      # ä½ çš„ç¤¾äº¤ ID
      id = "346521888@qq.com"
      # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
      prefix = ""
      # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
      title = "Email"
    [params.social.GitHub]
      # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
      weight = 0
      # ä½ çš„ç¤¾äº¤ ID
      id = "kevinchen1994"
      # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
      prefix = "https://github.com/"
      # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
      title = "GitHub"


# paper é…ç½®
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page


