baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "PaperMod"
# é»˜è®¤æ¯é¡µåˆ—è¡¨æ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®
paginate = 10
# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."




# èœå•é…ç½®
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "æ‰€æœ‰æ–‡ç« "
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "æ ‡ç­¾"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "ç±»åˆ«"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "ç³»åˆ—"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    name = ""
    url = "https://github.com/kevinchen1994"
    weight = 10

[params]
# ä¸»é¡µä¿¡æ¯è®¾ç½®
  [params.home]
    [params.home.profile]
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title = "kevin"
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
      subtitle = "ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer"
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
      # Gravatar é‚®ç®±ï¼Œç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail = "346521888@qq.com"

# æ–‡ç« é¡µé¢é…ç½®
[page]
  # æ˜¯å¦ä½¿ç”¨ç³»åˆ—å¯¼èˆª
  seriesNavigation = true
  # æ˜¯å¦å¯ç”¨æœ€åä¿®æ”¹æ—¶é—´
  enableLastMod = true
  # æ˜¯å¦å¯ç”¨å­—æ•°ç»Ÿè®¡
  enableWordCount = true
  # æ˜¯å¦å¯ç”¨é˜…è¯»æ—¶é—´ä¼°è®¡
  enableReadingTime = true
   # ç›®å½•é…ç½®
  [page.toc]
    # æ˜¯å¦ä½¿ç”¨ç›®å½•
    enable = true
    # æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
    keepStatic = false
    # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
    auto = true
  # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
  [page.share]
    enable = true
    Twitter = true
    Weibo = true
  # è¯„è®ºç³»ç»Ÿè®¾ç½®
  [page.comment]
    enable = true
    # Utterances comment è¯„è®ºç³»ç»Ÿè®¾ç½® (https://utteranc.es/)
    [page.comment.utterances]
      enable = true
      # owner/repo
      repo = "Hugo-DoIt/utterances-comments"
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"

# ç½‘ç«™åˆ†æé…ç½®
[analytics]
  enable = true
  # Google Analytics
  [analytics.google]
    id = ""
    # æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
    anonymizeIP = true

# paper é…ç½®
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page


