baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "DoIt"
# é»˜è®¤æ¯é¡µåˆ—è¡¨æ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®
paginate = 10
# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
subtitle = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'



# Menu config
# èœå•é…ç½®

[[main]]
  identifier = "posts"
  # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
  pre = ""
  # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
  post = ""
  name = "æ‰€æœ‰æ–‡ç« "
  url = "/posts/"
  # å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶å°†æ˜¾ç¤ºæ ‡é¢˜ã€‚
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "æ ‡ç­¾"
  url = "/tags/"
  title = ""
  weight = 2
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "åˆ†ç±»"
  url = "/categories/"
  title = ""
  weight = 3
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "ç³»åˆ—"
  url = "/series/"
  title = ""
  weight = 4
[[main]]
  identifier = "authors"
  pre = ""
  post = ""
  name = "ä½œè€…"
  url = "/authors/"
  title = ""
  weight = 5
[[main]]
  identifier = "showcase"
  pre = ""
  post = ""
  name = "ä½œå“"
  url = "/showcase/"
  title = ""
  weight = 6
[[main]]
  identifier = "documentation"
  pre = ""
  name = "æ–‡æ¡£"
  url = "/categories/documentation/"
  title = ""
  weight = 7
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "å…³äº"
  url = "/about/"
  title = ""
  weight = 8
[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github fa-fw'></i>"
  post = ""
  name = ""
  url = "https://github.com/kevinchen1994"
  title = "GitHub"
  weight = 9


[params.home.profile]
  # Gravatar é‚®ç®±, ç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
  gravatarEmail = "346521888@qq.com"
  # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
  avatarURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"
  # å¤´åƒçš„é“¾æ¥æŒ‡å‘çš„ URL
  avatarLinkURL = "https://s1.ax1x.com/2023/08/15/pPQAI4H.png"

[params.social]
  [params.social.email]
    # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
    weight = 10
    # ä½ çš„ç¤¾äº¤ ID
    id = "346521888@qq.com"
    # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
    prefix = ""
    # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
    title = "Email"
  [params.social.github]
    # æ’åˆ—å›¾æ ‡æ—¶çš„æƒé‡ (æƒé‡è¶Šå¤§, å›¾æ ‡çš„ä½ç½®è¶Šé å)
    weight = 0
    # ä½ çš„ç¤¾äº¤ ID
    id = "kevinchen1994"
    # ä½ çš„ç¤¾äº¤é“¾æ¥çš„å‰ç¼€
    prefix = "https://github.com/"
    # å½“é¼ æ ‡åœç•™åœ¨å›¾æ ‡ä¸Šæ—¶çš„æç¤ºå†…å®¹
    title = "GitHub"


# paper é…ç½®
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page

# ------------------------------
# é…ç½®ç½‘ç«™èœå•
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10
#  [[menu.main]]
#    identifier = "friends"
#    name = "Friends"
#    url = "/friends/"
#    weight = 10
