baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "Dolt"

author = "KevinChen"
DefaultContentLanguage = "zh"
paginate = 10
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = true


# paper é…ç½®
#[params]
#  color = 'linen'
#  github = 'kevinchen1994'
#  avatar = 'https://s1.ax1x.com/2023/08/15/pPQAI4H.png'
#  name = 'KevinChen'
#  bio = 'ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer'
  # misc
#  disableHLJS = true                        # disable highlight.js
#  monoDarkIcon = true                       # show monochrome dark 
#  comments = true                            # disable comments for a specific page
#  math = true                                 # enable KaTex math typesetting for a specific page

# ------------------------------
# é…ç½®ç½‘ç«™èœå•
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10
#  [[menu.main]]
#    identifier = "friends"
#    name = "Friends"
#    url = "/friends/"
#    weight = 10
