baseURL = "https://kevinchen1994.github.io/"
languageCode = "en-us"
title = "å¨å¸ˆæµ·æ£®å ¡çš„å¨æˆ¿"
theme = "hugo-PaperMod"

# ç‰ˆæƒæè¿°ï¼Œä»…ä»…ç”¨äº SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."


# home-info mode
[homeInfoParams]
  Title: "kevin"
  Content: ğŸ‘¨ğŸ»â€ğŸ’»çƒ­çˆ±ç”Ÿæ´»çš„ç¼–ç¨‹å°‘å¹´|ğŸƒä¸ä¸¥è‚ƒè·‘è€…|ğŸ§ NLPer


# èœå•é…ç½®
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "æ‰€æœ‰æ–‡ç« "
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "æ ‡ç­¾"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "ç±»åˆ«"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "series"
    name = "ç³»åˆ—"
    url = "/series/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 5
